#!/bin/sh
# This script ensures that i3 will spawn a calculator.
# If R is installed, it will run R, otherwise it will run
# Python.
([ -e /usr/bin/R ] && R -q --no-save) || python
# It used to be python -q which is an invalid option, should look into that.
([ -e /usr/bin/R ] && R -q --no-save) || python -q
